// A real Android app that calls a C library through JNI bindings generated by the plugin.
// Both plugins are applied to this one module: the konan plugin produces the .a + the JNI stub .so
// + the Kotlin bridges; AGP packages the .so and compiles the app.

plugins {
    id("com.android.application") // AGP 9 has built-in Kotlin support
    id("io.github.lemcoder.konanplugin")
}

val konanHome: String = System.getenv("KONAN_HOME")
    ?: file("${System.getProperty("user.home")}/.konan")
        .listFiles { f -> f.isDirectory && f.name.startsWith("kotlin-native-prebuilt-") }
        ?.maxByOrNull { it.name }?.absolutePath
    ?: error("No Kotlin/Native distribution found. Set KONAN_HOME.")

// Device (arm64) + emulator (x86_64).
val androidTargets = listOf("android_arm64", "android_x64")

// 1) Cross-compile native/*.c -> build/native/<target>/libmymath.a per ABI.
konanConfig {
    konanPath.set(konanHome)
    targets.set(androidTargets)
    sourceDir.set("native")
    headerDir.set("native")
    libName.set("mymath")
    outputDir.set("build/native")
    additionalCompilerArgs.set(listOf("-std=c99"))
}

// 2) Generate JNI bridges + link a self-contained stub .so per ABI.
jvmInterop {
    headers.set(listOf("mymath.h"))
    packageName.set("example")
    headerDir.set("native")
    targets.set(androidTargets)
    staticLibraryDir.set("build/native")
    staticLibraryName.set("mymath")
}

android {
    namespace = "com.example.jniapp"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.example.jniapp"
        minSdk = 21          // matches the NDK __ANDROID_API__=21 the stubs are built against
        targetSdk = 36
        versionCode = 1
        versionName = "1.0"
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    // Consume the plugin's outputs: generated Kotlin bridges + the per-ABI .so libraries.
    // AGP 9 disallows Providers here; task ordering is handled by the dependsOn wiring below.
    sourceSets["main"].kotlin.srcDir(layout.buildDirectory.dir("generated/jvmInterop/kotlin").get().asFile)
    sourceSets["main"].jniLibs.srcDir(layout.buildDirectory.dir("jvmInterop/jniLibs").get().asFile)
}

// --- task wiring ---
androidTargets.forEach { t ->
    tasks.matching { it.name == "linkJvmInterop${t.replaceFirstChar { c -> c.uppercase() }}" }
        .configureEach { dependsOn("runKonanClang") }
}
// Generate the bridges before Kotlin compiles, and build the .so before AGP packages it.
tasks.matching { it.name.startsWith("compile") && it.name.contains("Kotlin") }
    .configureEach { dependsOn("generateJvmInterop") }
tasks.matching { it.name == "preBuild" }
    .configureEach { dependsOn("linkJvmInterop") }
