// A real Android app that calls a C library through JNI bindings generated by the plugin.
// Both plugins are applied to this one module: the konan plugin produces the .a + the JNI stub .so
// + the Kotlin bridges; AGP packages the .so and compiles the app.

import org.jetbrains.kotlin.konan.target.KonanTarget
import io.github.lemcoder.interop.jvmInterops

plugins {
    id("com.android.application") // AGP 9 has built-in Kotlin support
    id("io.github.lemcoder.konanplugin")
}

// konanConfig compiles only: native/*.c -> build/native/<target>/libmymath.a per ABI. The
// Kotlin/Native distribution is auto-detected ($KONAN_HOME, else the newest ~/.konan/kotlin-native-prebuilt-*).
konanConfig {
    targets(KonanTarget.ANDROID_ARM64, KonanTarget.ANDROID_X64) // device + emulator
    libName.set("mymath")
}

// An AGP module has no Kotlin compilation to hang interops on, so they are declared on the project;
// the generated bindings and the per-ABI jniLibs are wired into the variants. The archive to link
// defaults to what konanConfig built for each target.
jvmInterops {
    create("mymath") {
        defFile(project.file("src/main/nativeInterop/mymath.def"))
        includeDirs.from(file("native"))
        targets.set(listOf(KonanTarget.ANDROID_ARM64, KonanTarget.ANDROID_X64))
    }
}

android {
    namespace = "com.example.jniapp"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.example.jniapp"
        minSdk = 21          // matches the NDK __ANDROID_API__=21 the stubs are built against
        targetSdk = 36
        versionCode = 1
        versionName = "1.0"
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

// That's it — the plugin auto-wires the generated Kotlin bridges + per-ABI jniLibs into AGP and
// orders generateJvmInteropMymath / linkJvmInteropMymath / runKonanClang before the build.
