package io.github.lemcoder

import org.gradle.testkit.runner.GradleRunner
import java.io.File
import kotlin.io.path.createTempDirectory
import kotlin.test.Test
import kotlin.test.assertFalse
import kotlin.test.assertTrue

/**
 * Black-box functional tests: apply the plugin to a throwaway build via TestKit and drive its tasks
 * with `--dry-run`, so the task graph is configured and wired but no real Kotlin/Native toolchain is
 * needed. `withPluginClasspath()` injects the plugin-under-test (auto-generated by java-gradle-plugin).
 */
class KonanPluginFunctionalTest {

    private val projectDir = createTempDirectory("konan-testkit").toFile()
    private val settingsFile get() = File(projectDir, "settings.gradle.kts")
    private val buildFile get() = File(projectDir, "build.gradle.kts")

    private fun runner(vararg args: String) = GradleRunner.create()
        .withProjectDir(projectDir)
        .withPluginClasspath()
        .withArguments(*args)

    // A dummy KONAN_HOME so configuration that reads konanPath resolves without a real distribution.
    private fun konanStub(): String {
        val home = File(projectDir, "konan-stub").apply { mkdirs() }
        return home.absolutePath.replace("\\", "/")
    }

    private fun writeBuild(name: String, konanConfig: String) {
        settingsFile.writeText("""rootProject.name = "$name"""")
        buildFile.writeText(
            """
            import io.github.lemcoder.KonanTarget
            import io.github.lemcoder.interop.jvmInterops

            plugins {
                id("io.github.lemcoder.konanplugin")
            }

            konanConfig {
                konanPath.set("${konanStub()}")
            ${konanConfig.trimIndent().prependIndent("    ")}
            }
            """.trimIndent()
        )
    }


    /** As [writeBuild], plus a `jvmInterops { }` block and the def it points at. */
    private fun writeInteropBuild(name: String, konanConfig: String, interops: String) {
        writeBuild(name, konanConfig)
        File(projectDir, "mymath.def").writeText("headers = mymath.h\npackage = example\n")
        File(projectDir, "mymath.h").writeText("int my_add(int a, int b);\n")
        buildFile.appendText(
            "\n\njvmInterops {\n" + interops.trimIndent().prependIndent("    ") + "\n}\n"
        )
    }

    @Test
    fun `registers runKonanClang and configures it without a real toolchain`() {
        writeBuild(
            "konan-fixture",
            """
            targets(KonanTarget.MACOS_ARM64)
            libName.set("mymath")
            """
        )

        val result = runner("runKonanClang", "--dry-run").build()

        // Dry-run realizes + configures the task graph but skips the @TaskAction. Dry-run tasks are
        // not "executed", so they show up in the output rather than in result.task(...).
        assertTrue(
            result.output.contains(":runKonanClang SKIPPED"),
            "expected runKonanClang in the configured dry-run graph, got:\n${result.output}"
        )
    }

    @Test
    fun `sourceDir, headerDir, libName and outputDir have conventions`() {
        // Only the targets are declared: everything else must come from a convention, and the build
        // must still configure. libName defaults to the project name.
        writeBuild("convention-fixture", """targets(KonanTarget.MACOS_ARM64)""")

        val result = runner("runKonanClang", "--dry-run").build()

        assertTrue(
            result.output.contains(":runKonanClang SKIPPED"),
            "expected runKonanClang to configure from conventions alone, got:\n${result.output}"
        )
    }

    @Test
    fun `an interop declared on the project registers generate and per-target link tasks`() {
        writeInteropBuild(
            "interop-fixture",
            konanConfig = """
            targets(KonanTarget.MACOS_ARM64)
            libName.set("mymath")
            """,
            interops = """
            create("mymath") {
                defFile(project.file("mymath.def"))
            }
            """,
        )

        val result = runner("linkJvmInteropMymath", "--dry-run").build()

        assertTrue(
            result.output.contains(":generateJvmInteropMymath SKIPPED"),
            "expected the generate task in the dry-run graph, got:\n${result.output}"
        )
        assertTrue(
            result.output.contains(":linkJvmInteropMymathMacos_arm64 SKIPPED"),
            "expected a per-target link task in the dry-run graph, got:\n${result.output}"
        )
        // The per-target link task must depend on the .a it links.
        assertTrue(
            result.output.contains(":runKonanClang SKIPPED"),
            "expected runKonanClang to be a dependency of the link task, got:\n${result.output}"
        )
    }

    @Test
    fun `interop targets are independent of the konanConfig ones`() {
        writeInteropBuild(
            "android-fixture",
            konanConfig = """
            targets(KonanTarget.ANDROID_ARM64, KonanTarget.ANDROID_X64)
            libName.set("mymath")
            """,
            interops = """
            create("mymath") {
                defFile(project.file("mymath.def"))
                targets.set(listOf(KonanTarget.ANDROID_ARM64, KonanTarget.ANDROID_X64))
            }
            """,
        )

        val result = runner("linkJvmInteropMymath", "--dry-run").build()

        assertTrue(
            result.output.contains(":linkJvmInteropMymathAndroid_arm64 SKIPPED"),
            "expected an arm64 link task, got:\n${result.output}"
        )
        assertTrue(
            result.output.contains(":linkJvmInteropMymathAndroid_x64 SKIPPED"),
            "expected an x64 link task, got:\n${result.output}"
        )
    }

    @Test
    fun `konanConfig alone registers no interop tasks`() {
        writeBuild(
            "no-interop-fixture",
            """
            targets(KonanTarget.MACOS_ARM64)
            libName.set("mymath")
            """
        )

        val result = runner("tasks", "--group=interop").build()

        assertFalse(
            result.output.contains("generateJvmInterop"),
            "expected no interop tasks without a jvmInterops block, got:\n${result.output}"
        )
    }
}
