package io.github.lemcoder

import org.gradle.testkit.runner.GradleRunner
import java.io.File
import kotlin.io.path.createTempDirectory
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * Black-box functional tests: apply the plugin to a throwaway build via TestKit and drive its tasks
 * with `--dry-run`, so the task graph is configured and wired but no real Kotlin/Native toolchain is
 * needed. `withPluginClasspath()` injects the plugin-under-test (auto-generated by java-gradle-plugin).
 */
class KonanPluginFunctionalTest {

    private val projectDir = createTempDirectory("konan-testkit").toFile()
    private val settingsFile get() = File(projectDir, "settings.gradle.kts")
    private val buildFile get() = File(projectDir, "build.gradle.kts")

    private fun runner(vararg args: String) = GradleRunner.create()
        .withProjectDir(projectDir)
        .withPluginClasspath()
        .withArguments(*args)

    // A dummy KONAN_HOME so configuration that reads konanPath resolves without a real distribution.
    private fun konanStub(): String {
        val home = File(projectDir, "konan-stub").apply { mkdirs() }
        return home.absolutePath.replace("\\", "/")
    }

    @Test
    fun `registers runKonanClang and configures it without a real toolchain`() {
        settingsFile.writeText("""rootProject.name = "konan-fixture"""")
        buildFile.writeText(
            """
            plugins {
                id("io.github.lemcoder.konanplugin")
            }

            konanConfig {
                konanPath.set("${konanStub()}")
                targets.set(listOf("macos_arm64"))
                sourceDir.set("native")
                headerDir.set("native")
                libName.set("mymath")
                outputDir.set("build/native")
            }
            """.trimIndent()
        )

        val result = runner("runKonanClang", "--dry-run").build()

        // Dry-run realizes + configures the task graph but skips the @TaskAction. Dry-run tasks are
        // not "executed", so they show up in the output rather than in result.task(...).
        assertTrue(
            result.output.contains(":runKonanClang SKIPPED"),
            "expected runKonanClang in the configured dry-run graph, got:\n${result.output}"
        )
    }

    @Test
    fun `jvmInterop wires a per-target link task under the linkJvmInterop umbrella`() {
        settingsFile.writeText("""rootProject.name = "interop-fixture"""")
        buildFile.writeText(
            """
            plugins {
                id("io.github.lemcoder.konanplugin")
            }

            // The plugin always registers runKonanClang, so konanConfig must be present too.
            konanConfig {
                konanPath.set("${konanStub()}")
                targets.set(listOf("macos_arm64"))
                sourceDir.set("native")
                headerDir.set("native")
                libName.set("mymath")
                outputDir.set("build/native")
            }

            jvmInterop {
                konanPath.set("${konanStub()}")
                headers.set(listOf("mymath.h"))
                packageName.set("example")
                headerDir.set("native")
                targets.set(listOf("macos_arm64"))
                staticLibraryDir.set("build/native")
                staticLibraryName.set("mymath")
            }
            """.trimIndent()
        )

        val result = runner("linkJvmInterop", "--dry-run").build()

        // afterEvaluate registers linkJvmInterop<Target> and makes it a dependency of the umbrella.
        assertTrue(
            result.output.contains(":linkJvmInterop SKIPPED"),
            "expected the umbrella link task in the dry-run graph, got:\n${result.output}"
        )
        assertTrue(
            result.output.contains(":linkJvmInteropMacos_arm64 SKIPPED"),
            "expected a per-target link task in the dry-run graph, got:\n${result.output}"
        )
    }
}
