package io.github.lemcoder.jvm

private val JVM_NAME = Regex("""@file:JvmName\("([^"]+)"\)""")
private val EXTERN = Regex("""(?m)^\s*(?:private\s+)?external\s+fun\s+(kniBridge\d+)\s*\(([^)]*)\)\s*:\s*(\S+)\s*$""")
private val LOAD_LIB = Regex("""loadKonanLibrary\("([^"]+)"\)""")
// Captures each friendly wrapper's name/params/return and the kniBridge it delegates to, so we can keep
// the original C-derived signature as documentation next to the otherwise opaque bridge.
private val WRAPPER = Regex("""(?s)fun\s+(\w+)\(([^)]*)\)\s*:\s*([^{]+?)\s*\{[^}]*?kniBridge(\d+)""")

/**
 * Rewrites a cinterop-generated JVM `.kt` into a runtime-free form: keeps `@file:JvmName` + package +
 * the `external fun kniBridgeN` declarations (so the JNI symbol mapping is preserved), erases the
 * `NativePtr` typealias to `Long`, replaces `loadKonanLibrary` with `System.loadLibrary`, and drops
 * the `kotlinx.cinterop` wrappers/imports entirely.
 */
fun stripCinterop(src: String): String {
    val jvmName = JVM_NAME.find(src)?.groupValues?.get(1)
    val pkg = src.lineSequence().firstOrNull { it.trimStart().startsWith("package ") }?.trim()
    val libName = LOAD_LIB.find(src)?.groupValues?.get(1)
        ?: error("Generated .kt has no loadKonanLibrary(...) call; cannot determine native library name.")

    // bridge index -> original C-derived signature (for documentation).
    val origByBridge = WRAPPER.findAll(src).associate { m ->
        val name = m.groupValues[1]
        val params = m.groupValues[2].trim()
        val ret = m.groupValues[3].trim()
        m.groupValues[4] to "$name($params): $ret"
    }

    val externs = EXTERN.findAll(src).map { m ->
        val bridge = m.groupValues[1]
        val idx = bridge.removePrefix("kniBridge")
        val params = m.groupValues[2].replace("NativePtr", "Long")
        val ret = m.groupValues[3].replace("NativePtr", "Long")
        val doc = origByBridge[idx]?.let { "/** C: $it */\n" } ?: ""
        "${doc}external fun $bridge($params): $ret"
    }.toList()

    return buildString {
        jvmName?.let { appendLine("""@file:JvmName("$it")""") }
        appendLine("""@file:Suppress("FunctionName", "unused")""")
        pkg?.let { appendLine(it) }
        appendLine()
        appendLine("// AUTO-GENERATED runtime-free JNI bridges. Do not edit; regenerated by generateJvmInterop.")
        appendLine("// Pointers are passed as raw addresses (Long). Write your idiomatic expect/actual on top.")
        appendLine()
        appendLine("""private val nativeLibrary: Unit = System.loadLibrary("$libName")""")
        appendLine()
        externs.forEach { appendLine(it) }
    }
}